name: Image Scanner

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
      # Set skip-image-build to true, to scan the latest image from the registry else set to false for building the image and scanning it
      skip-image-build:
        required: false
        type: boolean
        default: false
      # To pull image from the registry, specify image name when skip-image-build flag is set to true.
      image:
        required: false
        type: string
      ignore-unfixed:
        required: false
        type: boolean
        default: true
      skip-cves-scan:
        required: false
        type: boolean
        default: false
      skip-license-scan:
        required: false
        type: boolean
        default: false
      skip-code-license-scan:
        required: false
        type: boolean
        default: true
    secrets:
      ICR_USERNAME:
        required: false
      ICR_APIKEY:
        required: false

env:
  IMAGE_FILE_NAME: image.tar
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd
  TRIVY_SBOM_FILE: trivy.json
  PARLAY_SBOM_FILE: parlay.json
  PARLAY_VERSION: v0.9.0

jobs:
  cves:
    runs-on: ubuntu-24.04-ppc64le
    if: ${{ !inputs['skip-cves-scan'] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build image
        if: ${{ !inputs.skip-image-build }}
        working-directory: ${{ inputs.path }}
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} REGISTRY_USER=${{ secrets.ICR_USERNAME }} REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}

      - name: Pull latest image Tag
        if: ${{ inputs.skip-image-build }}
        working-directory: ${{ inputs.path }}
        id: image-tag
        run: |
          TAG_VALUE=$(make image-tag)
          IMAGE_NAME=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}/${{ inputs.image }}:${TAG_VALUE}
          podman pull --creds ${{ secrets.ICR_USERNAME }}:${{ secrets.ICR_APIKEY }} $IMAGE_NAME

      - name: Save image in file
        run: |
          IMAGE_NAME=$(podman images --format "{{.Repository}}:{{.Tag}}" | grep "${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}" | head -n 1)
          podman save > ${{ env.IMAGE_FILE_NAME }} $IMAGE_NAME

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          input: ${{ env.IMAGE_FILE_NAME }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: ${{ inputs.ignore-unfixed }}

  license:
    runs-on: ubuntu-24.04-ppc64le
    if: ${{ !inputs['skip-license-scan'] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build image
        if: ${{ !inputs.skip-image-build }}
        working-directory: ${{ inputs.path }}
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} REGISTRY_USER=${{ secrets.ICR_USERNAME }} REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}
      
      - name: Pull latest image tag
        if: ${{ inputs.skip-image-build && inputs.skip-code-license-scan }}
        working-directory: ${{ inputs.path }}
        run: |
          TAG_VALUE=$(make image-tag)
          IMAGE_NAME=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}/${{ inputs.image }}:${TAG_VALUE}
          podman pull --creds ${{ secrets.ICR_USERNAME }}:${{ secrets.ICR_APIKEY }} $IMAGE_NAME

      - name: Save image in file
        if: ${{ inputs.skip-code-license-scan }}
        run: |
          IMAGE_NAME=$(podman images --format "{{.Repository}}:{{.Tag}}" | grep "${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}" | head -n 1)
          podman save > ${{ env.IMAGE_FILE_NAME }} $IMAGE_NAME

      - name: Generate trivy sbom scan report for images
        if: ${{ inputs.skip-code-license-scan }}
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: image
          input: ${{ env.IMAGE_FILE_NAME }}
          format: cyclonedx
          output: ${{ env.TRIVY_SBOM_FILE }}
      
      - name: Generate trivy sbom scan report for ai-services code
        if: ${{ !inputs.skip-code-license-scan }}
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          input: './ai-services'
          format: cyclonedx
          output: ${{ env.TRIVY_SBOM_FILE }}

      - name: Enrich trivy SBOM with parlay
        run: |
          mkdir -p $HOME/bin
          wget https://github.com/snyk/parlay/releases/download/${{ env.PARLAY_VERSION }}/parlay_Linux_ppc64le.tar.gz
          tar -xzf parlay_Linux_ppc64le.tar.gz
          chmod +x parlay
          mv parlay $HOME/bin
          export PATH=$HOME/bin:$PATH
          parlay --version
          parlay ecosystems enrich ${{ env.TRIVY_SBOM_FILE }} | jq . > ${{ env.PARLAY_SBOM_FILE }}

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json-artifact
          path: |
            ${{ env.TRIVY_SBOM_FILE }}
            ${{ env.PARLAY_SBOM_FILE }}

      - name: Licenses scan
        run: python .github/scripts/license_scan.py ${{ env.TRIVY_SBOM_FILE }} ${{ env.PARLAY_SBOM_FILE }}
